author: Nate Smith
exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
highlighter: rouge
markdown: kramdown
sass:
  style: compressed
title: The Internate
url: http://theinternate.com
