author: Nate Smith
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - bin/
  - circle.yml
  - vendor/
gem:
  - jekyll-sass-converter
  - jekyll-sitemap
highlighter: rouge
markdown: kramdown
sass:
  style: compressed
title: The Internate
url: http://theinternate.com
