version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile.lock" }}
            - bundle-v1-
      - run:
          name: Install dependencies
          command: gem install bundler --version=2.1.4
      - run:
          name: Install dependencies
          command: |
            bundle check --path vendor/bundle ||
              bundle install --path vendor/bundle
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - run: bin/rake ci
