version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby
  working_directory: /code
  steps:
    - checkout
    - run: bundle install
    - run: bin/rake ci

workflows:
  version: 2
  pipeline:
    jobs:
      - build
