version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: gem install bundler --version=2.1.4
      - run: bundle install
      - run: bin/rake ci
